apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: skaffold-example
manifests:
  rawYaml:
    - deployment.yaml
    - svc.yaml
  transform:
  - name: set-labels
    configMap:
     - "env:dev"
deploy:
  kpt: {}


